# Generated by Django 2.1.15 on 2025-03-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodapp',
            new_name='career_in',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='course_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ST', 'String'), ('RT', 'Rhytym'), ('VO', 'Vocal'), ('PR', 'Prodution'), ('CO', 'Composition'), ('MG', 'Management')], max_length=2),
        ),
    ]
