# Generated by Django 2.1.15 on 2025-03-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
    ]
