version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Upgrading pip"
      - pip install --upgrade pip
      - echo "Installing from root requirements.txt"
      - pip install -r ./requirements.txt pylint

  pre_build:
    commands:
      - echo "Running Python version:"
      - python --version
      - echo "Linting files..."
      - pylint *.py || true
      - pylint devopsPro/*.py || true
      - pylint devopsPro/app/*.py || true

artifacts:
  base-directory: devopsPro
  files:
    - '**/*'
