version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Upgrading pip..."
      - pip install --upgrade pip
      - echo "Installing dependencies..."
      - pip install -r requirements.txt pylint

  pre_build:
    commands:
      - echo "Checking Python version..."
      - python --version
      - echo "Running Pylint..."

artifacts:
  base-directory: .
  files:
    - '**/*'
