version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:

  pre_build:
    commands:
      - echo "Checking Python version..."
      - python --version
      - python manage.py collectstatic --noinput

artifacts:
  base-directory: .
  files:
    - '**/*'

