version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:

  pre_build:
    commands:
      - echo "Checking Python version..."
      - python --version
      

artifacts:
  base-directory: .
  files:
    - '**/*'

# env:
# sonar-scanner \
#   -Dsonar.organization=x23244119 \
#   -Dsonar.projectKey=lordjdsama_x23244119April2025 \
#   -Dsonar.sources=. \
#   -Dsonar.host.url=https://sonarcloud.io
  
