version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies with verbose logging..."
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint || true  # <--- allow build to continue

  pre_build:
    commands:
      - echo "Pre-build checks..."
      - python --version

artifacts:
  base-directory: .
  files:
    - '**/*'
